config/routes.rb
Findsimilar::Application.routes.draw do

  match 'auth/:provider/callback', to: 'sessions#create'
  match 'auth/failure', to: redirect('/')
  match 'signout', to: 'sessions#destroy', as: 'signout'
  
  resources :questions do
    collection do
    end
  end
 
  resources :answers do

  end
  
  resources :likes do
  end

  resources :votes do
  end
  match 'profile' => 'welcome#profile', :as => :profile
  match '/view/:id', to: 'welcome#view'
  match 'update_answer', to: 'answers#update_answer',as: 'update_answer'
  match 'post_question', to: 'welcome#post_question', as: 'post_question'
  match 'update_like_status', to: 'likes#update_like_status', as: 'update_like_status'
  match 'follow_user_path', to: 'welcome#follow_user', as: 'follow_user'
  match 'follow_question_path', to: 'welcome#follow_question', as: 'follow_question'
  root :to => "welcome#index"
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  #GET index 
  def index
    #@questions = Question.find(:all,:order => "created_at DESC")
    @questions = Question
                  .select("*")
                  .order("created_at DESC")
                  .paginate(:page => params[:page],:per_page=>10)
    @page = @questions.current_page 
    logger.debug "next page is #{@page}"

    @question = Question.find(params[:name]).question if params[:question_id]
    logger.debug "question is #{@question}"
    respond_to do |format|
      format.html 
      format.json { render json: @questions }
    end
  
  end
  
  def view
    @question = Question.find(params[:id])
    @answer = @question.answers.new
    #@answers = Answer.where("question_id = ?", @question.id).order("created_at DESC")
    @answers = Answer
      .select("answers.*,questions.user_id as user_id")
      .joins(:question).where("question_id = ?", @question.id)
      .order("answers.created_at DESC")
      .paginate(:page => params[:page],:per_page=>10)
      
    @vote = @answer.votes.new
    respond_to do |format|
      format.html
      format.json { render json: @question }
    end
  end

  def profile
    @questions = Question.where("user_id=?",current_user.id)
    @answers = Answer.where("user_id=?",current_user.id)
    @user = current_user.id
    @accepted_answers = Answer.where("user_id=? and is_accepted=?",current_user.id,true)

     respond_to do |format|
      format.html
      format.json { render json: @question }
    end
  end
  
  def post_question
    @question = Question.find(params[:id])
    @question_name = @question.question
    @question_image = @question.image.thumb

    respond_to do |format|
        format.js { render :layout => false }
      end
  end

  def follow_user
    @question = Question.find(params[:question_id])
    @follower = current_user
    @followable = User.find(@question.user_id)
    @follower.follow(@followable)
    respond_to do |format|
      format.js { render :layout => false  }
    end
  end

  def follow_question
    @questions = Question.find(:all)
    @question = Question.find(params[:question_id])
    @follower = current_user
    @follower.follow(@question)
    respond_to do |format|
      format.js { render :layout => false  }
    end
  end

end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/_commentlist.html.erb
<% @answers.each do |answer| %>
  <ol id="comment-list" class="group">
  <li class="comment">
    <span class="comment-meta">Posted by <strong><%= answer.user.name if answer.user %></strong>, at
      <time> 
      	<%= answer.updated_at %>
      </time>
    </span>

    <div class="comment-text group">
    	<img class="avatar avatar-image" src="<%= answer.image %>" alt="">
    	<div class="comment-copy" id="comment-image">
      	<p>
          <%= answer.comment %>
        </p>
        <div class = "comment_vote">
        	<%if current_user %>
          	<%= link_to "Buy this", answer.url,  :TARGET => '_blank' %>
          	<% vote = Vote.where("answer_id=? and user_id=?",answer.id,current_user.id).length %>
          	<%= link_to_if vote == 0, "vote up", votes_path(:answer_id => answer.id, :is_vote => true), :method => "post", :remote => true, :class => "comment_vote" %>
            <%  like = Like.find_by_user_id_and_answer_id(current_user.id, answer.id) rescue nil %>
            <%  if like.present? and like.is_like == true %>
            	<%= link_to "Unlike", update_like_status_path(:answer_id => answer.id, :user_id => current_user.id), :remote => true %>
            <% else %>
            	<%  if answer.likes.present? %>
              	<%= link_to "Like", update_like_status_path(:answer_id => answer.id, :user_id => current_user.id), :remote => true %>
                <% else %>
                  <%= link_to "Like", likes_path(:answer_id => answer.id, :user_id => current_user.id), :method => "post", :remote => true %>
              <% end %>
            <% end %>
            <% if answer.user_id == current_user.id %>
              <% answer_accepted = Answer.where("question_id=? and user_id=? and is_accepted=?",answer.question_id,answer.user_id,true).length %>
              <%= link_to_if answer_accepted == 0, "Accept Answer",update_answer_path(:answer_id => answer.id,:question_id => answer.question_id),:class=>"answer-comment",:remote=>true %>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
  </li>
<% end %>
<%= will_paginate @answers,:remote => true %>
<script>

$('.avatar-image').bind("mouseover",function(){
   $(this).animate({ 
    width: '100%',
    height: '100%'
    //queue: false
  },2000);
   $('#comment-image').hide();
 }).bind("mouseout",function(){
  $(this).animate({ 
    width: '65px',
    height: '65px'
   
  },1500);
   $('#comment-image').show();
});
// $('.avatar-image').hover(function(){
//   //alert('image clicked!');
//   $(this).animate({ 
//     width: '200px',
//     height: '200px'
//    // $(this).stop();
//   });
//})
</script>

app/views/welcome/_question.html.erb
<article class="entry box format-image">
	<div class="entry-intro">
		<h1><%= @question.question %></h1>
		<span class="entry-meta">Posted by <strong> <vmasto><%= @question.user.name%></strong>, at
			<time datetime="2012-08-07">
				<%= @question.created_at%>
			</time>
			<% if current_user %>
				<%  follower = Follow.find_by_follower_id_and_followable_id(current_user.id, @question.user_id) rescue nil %>
				<% if follower.present? %>
					<h5>You are following this user</h5>
				<% else %>
					<% if @question.user_id != current_user.id %>
						<%= link_to "follow User", follow_user_path(:question_id => @question.id), :remote => true%>
					<% end %>
				<% end %>
			<% end %>
		</span>
		<a class="single-heart-this" href="#" title="Love this."> <span class="heart-icon"></span> <span class="heart-no">16</span></a>
					<!-- .entry-intro -->
	</div>
	<figure class="entry-image">
		<a href="#" data-lightbox="fancybox"><img src="<%= @question.image.medium %>" alt="<%= @question.question %>"></a>
	</figure>
	<div class="entry-intro">
		<h1>Price : <%= number_to_currency(@question.price)%></h1>
		<h2>Description : <%= @question.description%></h2>
		<p>
			<strong>more details check </strong><a href="#"><%= @question.url%></a>
		</p>
	</div>
	<div class="social-share"></div>
</article>

app/views/welcome/_questionlist.html.erb
<%= will_paginate @questions,:remote => true,:class=>"apple_pagination"%>
<%# javascript :defaults, 'endless_page' %>
<% @questions.each do |question| %>

<article id="post-<%= question.id %>" class="category-people category-photography category-pretty-girls entry box format-image">

	<div class="entry-content-cnt">
		<div class="entry-content">
			<a href="/view/<%= question.id %>" class="thumb" title="<%= question.question %>"><img src="<%= question.image.thumb %>" class="attachment-ci_listing_thumb" alt="<%= question.question %>" title="<%= question.question %>"></a>
		</div>
	</div>

	<div class="entry-desc">
		<h1><a href="/view/<%= question.id %>" title="<%= question.question %>"><%= question.question %></a></h1>
		<p style="font-style: italic; text-align: right;margin-bottom: 2px">Posted by <%= question.user.name %></p>
		<h2 style="text-align: right"><a href="#" title="">Price willing <%= number_to_currency(question.price) %></a></h2>
    <div id="comment">
      <% if current_user %>
        <% if question.user_id == current_user.id %>
          <%= link_to 'Post Question on Facebook', post_question_path(:id=>question.id),:class=>'post-comment',:remote=>true %>
        <% end %>
      <% end %>
    </div>
		<!-- <p><a onclick='postToFeed(); return false; name="<%= question.id %>"'>Post to Feed</a></p> -->
    	<!-- <p id='msg'></p> -->
		<div id='fb-root'></div>
		<div class="entry-meta group">
			<a class="comments-no" href="#">4</a><a data-post-id="<%= question.id %>" class="heart-this loved" href="#" title="You love this."><span class="heart-no">7</span></a><a class="entry-permalink" href="#" title=""><%= question.question %></a>
      <%if current_user %>
        <% follower = Follow.find_by_follower_id_and_followable_id(current_user.id, question.id) rescue nil %>
        <% if follower.present? %>
          <h5> followed </h5>
        <% else %>
          <% if current_user.id != question.user_id %>
            <%= link_to " follow question", follow_question_path(:question_id => question.id), :remote => true %>
          <% end %>
        <% end %>
      <% end %>
		</div>
	</div>
</article>
<% end %>
 <script>
 
//  jQuery.ias({
//     container : '.entry-list',
//     item: '.category-people',
//     pagination: '.navigation',
//     //next: '.next-posts a',
//     loader: '<%= image_tag ("ajax-loader.gif")  %>'
// });
// $('.infinite-scroll').pageless({ totalPages: 10
//                        , //url: '/articles/'
//                        , loaderMsg: 'Loading more results'
//                        });
 //$('#infinite-scroll').jscroll();//{
//     loadingHtml: '<%= image_tag ("ajax-loader.gif")  %>',
//     padding: 100,
//     autoTrigger: true,
//     nextSelector: 'a.jscroll-next:last',
//     contentSelector: 'category-people'
// })
 </script>

app/views/welcome/follow_question.js.erb
$("#follow_question").html("<%= escape_javascript(render(:partial => 'questionlist')) -%> ");

app/views/welcome/follow_user.js.erb
$("#question").html("<%= escape_javascript(render(:partial => 'question')) -%> ");

app/views/welcome/index.html.erb
<div id="entry-listing" class="group">
	<article class="entry box isotope-item" id="intro">
		<div class="entry-content-cnt">
			<aside class="widget widget_ci_about_widget group">
				<h3 class="widget-title">What is find similiar??</h3>
				<div class="widget_about group">
					<!--<img alt="about me" class="alignleft" src="images/dummy/me.jpg"> -->
					<p>
						Lorem ipsum dolor sit amet, consectetur adipiscing elit. In lorem quam, gravida elementum nibh ut, scelerisque congue lectus. Sed dapibus elementum diam. Fusce malesuada iaculis velit, sollicitudin posuere elit vehicula vitae. Duis ut placerat erat, sed auctor est. Nulla lacinia magna sed sagittis malesuada. Praesent ac facilisis nisl, a semper odio. Mauris accumsan, risus et placerat rutrum, leo tellus dignissim metus, non mattis tortor nisi luctus metus.
					</p>

					<p>
						Try us out!
					</p>
				</div>
			</aside>

			<aside class="widget widget_ci_twitter_widget group">
				<h3 class="widget-title">Recent tweets</h3>
				<div id="twitter_update_list">
					<ul>
						<li>
							<span>@<a href="#">handle</a> Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce posuere tortor :)</span><a href="#" class="twitter-time">about 6 hours ago</a>
						</li>

						<li>
							<span>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce posuere tortor. <a href="#">http://www.example.com</a></span><a href="#" class="twitter-time">about 11 hours ago</a>
						</li>
					</ul>
				</div>
			</aside>
		</div>
	</article><!-- #intro -->
	<div id="infinite-scroll">
		<%= render :partial => 'questionlist' %>
	</div>
	<!-- <p id="loading"><%#= image_tag ("ajax-loader.gif")  %></p> -->
</div>

app/views/welcome/post_question.js.erb
      FB.init({appId: "670347169648397", status: true, cookie: true});
          
           $('.post-comment').click(function(){
              postToFeed();
            });  

      function postToFeed() {

        // calling the API ...
        var obj = {
        
          method: 'feed',
          redirect_uri: 'localhost:3000',
          link: 'localhost:3000/',
          picture: '<%= @question_image %>',
          name: 'Find Similar',
          caption: 'Post Question',
          description: '<%= @question_name %>'
        };

        function callback(response) {
          document.getElementById('msg').innerHTML = "Post ID: " + response['post_id'];
        }

        FB.ui(obj);
      }
    

app/views/welcome/profile.html.erb
<div id="entry-listing" class="group">
	<article class="entry box isotope-item" id="intro">
		<div class="entry-content-cnt">
			<aside class="widget widget_ci_about_widget group">
				<div class="widget_about group">
					<p>
						<%= image_tag current_user.image,:class=>'image-width' %>
						<h5 class="widget-title" style="margin-top: -23px;">Hi!! <%= current_user.name %></h5>
					</p>
				</div>
			</aside>
			<aside class="widget widget_ci_twitter_widget group">
				<h5 class="widget-title" style="margin-top: -23px;">Total Points: <%= current_user.points.presence ? current_user.points : "0" %></h5>
				<div id="twitter_update_list">
					<ul>
						<li>
							<span> Total Questions: <%= @questions.count.presence ? @questions.count : "0" %></span>
							
						</li>

						<li>
							<span> Total Answers: <%= @answers.count.presence ? @answers.count : "0" %></span>
							
						</li>
						<li>
							<span> <h5>Accepted Answers: <%= @accepted_answers.count.presence ? @accepted_answers.count : "0" %></h5></span>
							
						</li>
						<li>
							<span> <h4>Recent Answers </h4></span>
							<% @answers.each do |answer_comment| %>
								<div class="answer-recent">
									<div>
										<span style="word-wrap: break-word;">
											<%= answer_comment.comment %>
										</span><br/>
										<span class="comment-meta">Posted by <strong><%= answer_comment.user.name %></strong>
      									<time> 
      										<%= time_ago_in_words(answer_comment.updated_at) %> ago
      									</time>
      							</span>
									</div>
								</div>
							<% end %>
						</li>
					</ul>
				</div>
			</aside>
		</div>
	</article><!-- #intro -->
	
	<%= render :partial => 'questionlist' %>

	<div id="entry-listing" class="group" >
		<article class="entry box isotope-item" id="intro" style="float: right;" >
			<div class="entry-content-cnt" >
				<aside class="widget widget_ci_about_widget group">
					<div class="widget_about group">
						<p>
							<h5> followers: <%= current_user.followers_by_type_count('User') %></h5>
							<% current_user.followers_by_type('User').each do |follower| %>
								<%= follower.name %>
							<% end %>
							<h5> following: <%= current_user.following_by_type_count('User') %>  users</h5>
							<% current_user.following_by_type('User').each do |following| %>
								<br><%= following.name %></br>
							<% end %>
							<h5> following: <%= current_user.following_by_type_count('Question') %> questions</h5>
						</p>
					</div>
				</aside>			
			</div>
		</article><!-- #intro -->
	</div>
</div>
<script>
	$(".answer-recent").hover(function() { // mouseenter
	  $(this).addClass("answer-hover");
	}, function() { // mouseleave 
	  $(this).removeClass("answer-hover");
	});
</script>

app/views/welcome/view.html.erb
<div class="inner-container group">
	<div class="box-hold group">
		<%= render :partial => "question" %>
	</div><!-- .box-hold -->
	<div class="box-hold">
		<% if(@question.user_id != current_user.id) %>
			<div class="box comment-form">
				<div class="box-content">
		      <%= render :partial => "answers/comment" %>        
				</div>	
			</div>
		<%end %>

		<div class="box post-comments">
  		<div class="box-content">
    		<h1>Comments</h1>
      	<%= render :partial => "commentlist" %>
  		</div>
		</div>
	</div>
</div>

app/views/welcome/view1.html.erb
<div class="inner-container group">
	<div class="box-hold group">
		<article class="entry box format-image">
			<div class="entry-intro">
				
					<h1><%= @question.question %></h1><span class="entry-meta">Posted by <strong>
						<vmasto>
							<%= @question.user.name%>
						</strong>, at
						<time datetime="2012-08-07">
							<%= @question.created_at%>
						</time></span>
					<a class="single-heart-this" href="#" title="Love this."> <span class="heart-icon"></span> <span class="heart-no">16</span></a>
					<!-- .entry-intro -->
				
			</div>

			<figure class="entry-image">
				<a href="#" data-lightbox="fancybox"><img src="<%= @question.image.medium %>" alt="<%= @question.question %>"></a>
			</figure>
			<div class="entry-intro">
				<h1>Price : <%= number_to_currency(@question.price)%></h1>
				<h2>Description</h2>
				<%= @question.description%>

				<p>
					<strong>more details check </strong><a href="#"><%= @question.url%></a>
				</p>
			</div>
			<div class="social-share"></div>
		</article>
	</div><!-- .box-hold -->

	<div class="box-hold">
		<div class="box comment-form">
			<div class="box-content">
				<h3>Post your comment</h3>

				<form id="commentform" class="group" action="/">
					<fieldset class="group">
						<p>
							<input type="text" title="Your Name">
						</p>

						<p>
							<input type="text" title="Your E-mail">
						</p>
					</fieldset>

					<fieldset>
						<p>
							<textarea cols="30" rows="4" title="Your Comment"></textarea>
						</p>
					</fieldset>
					<button type="submit">
						Submit
					</button>
				</form>
			</div>
		</div>

		<div class="box post-comments">
			<div class="box-content">
				<h3>42 Comments</h3>

				<ol id="comment-list" class="group">
					<li class="comment">
						<span class="comment-meta">Posted by <strong>vmasto</strong>, at
							<time datetime="2012-08-07">
								July 7th, 2012
							</time> &mdash; <a class="comment-reply-link" href="#commentform">Reply</a></span>

						<div class="comment-text group">
							<img class="avatar" src="/assets/avatar.png" alt="">

							<div class="comment-copy">
								<p>
									First, I believe that this nation should commit itself to achieving the goal, before this decade is out, of landing a man on the moon and returning him safely to the earth. No single space project in this period will be more impressive to mankind, or more important for the long-range exploration.
								</p>
							</div>
						</div>
					</li>

					<li class="comment">
						<span class="comment-meta">Posted by <strong>vmasto</strong>, at
							<time datetime="2012-08-07">
								July 7th, 2012
							</time> &mdash; <a class="comment-reply-link" href="#commentform">Reply</a></span>

						<div class="comment-text group">
							<img class="avatar" src="/assets/avatar.png" alt="">

							<div class="comment-copy">
								<p>
									First, I believe that this nation should commit itself to achieving the goal, before this decade is out, of landing a man on the moon and returning him safely to the earth. No single space project in this period will be more impressive to mankind, or more important for the long-range exploration.
								</p>
							</div>
						</div>
					</li>

					<li class="comment">
						<span class="comment-meta">Posted by <strong>vmasto</strong>, at
							<time datetime="2012-08-07">
								July 7th, 2012
							</time> &mdash; <a class="comment-reply-link" href="#commentform">Reply</a></span>

						<div class="comment-text group">
							<img class="avatar" src="/assets/avatar.png" alt="">

							<div class="comment-copy">
								<p>
									First, I believe that this nation should commit itself to achieving the goal, before this decade is out, of landing a man on the moon and returning him safely to the earth. No single space project in this period will be more impressive to mankind, or more important for the long-range exploration.
								</p>
							</div>
						</div>
					</li>

					<li class="comment">
						<span class="comment-meta">Posted by <strong>vmasto</strong>, at
							<time datetime="2012-08-07">
								July 7th, 2012
							</time> &mdash; <a class="comment-reply-link" href="#commentform">Reply</a></span>

						<div class="comment-text group">
							<img class="avatar" src="/assets/avatar.png" alt="">

							<div class="comment-copy">
								<p>
									First, I believe that this nation should commit itself to achieving the goal, before this decade is out, of landing a man on the moon and returning him safely to the earth. No single space project in this period will be more impressive to mankind, or more important for the long-range exploration.
								</p>
							</div>
						</div>
					</li>
				</ol><a class="load-more-comments" href="#">View 38 More Comments...</a>
			</div>
		</div>
	</div><!-- .box-hold -->
</div>