config/routes.rb
Findsimilar::Application.routes.draw do

  match 'auth/:provider/callback', to: 'sessions#create'
  match 'auth/failure', to: redirect('/')
  match 'signout', to: 'sessions#destroy', as: 'signout'
  
  resources :questions do
    collection do
    end
  end
 
  resources :answers do

  end
  
  resources :likes do
  end

  resources :votes do
  end
  match 'profile' => 'welcome#profile', :as => :profile
  match '/view/:id', to: 'welcome#view'
  match 'update_answer', to: 'answers#update_answer',as: 'update_answer'
  match 'post_question', to: 'welcome#post_question', as: 'post_question'
  match 'update_like_status', to: 'likes#update_like_status', as: 'update_like_status'
  match 'follow_user_path', to: 'welcome#follow_user', as: 'follow_user'
  match 'follow_question_path', to: 'welcome#follow_question', as: 'follow_question'
  root :to => "welcome#index"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!--[if lt IE 7]> <html dir="ltr" lang="en-US" class="no-js lt-ie9 lt-ie8 lt-ie7" > <![endif]-->
<!--[if IE 7]>    <html dir="ltr" lang="en-US" class="no-js ie7 lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>    <html dir="ltr" lang="en-US" class="no-js ie8 lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!-->

<html dir="ltr" lang="en-US" class="no-js">
	<!--<![endif]-->
	<head>
		<meta charset="utf-8">
		<title>Find Similar</title>
		<%= stylesheet_link_tag    "application", :media => "all" %>
		<%= javascript_include_tag "application" %>
		<%= csrf_meta_tags %>
		<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
		<link href='http://fonts.googleapis.com/css?family=Lato:400,700,400italic|Yanone+Kaffeesatz' rel='stylesheet' type='text/css'>
		<script src='http://connect.facebook.net/en_US/all.js'></script>
		<link rel="stylesheet" href="/assets/style.css" type="text/css">
		<link rel="stylesheet" href="/assets/pink.css" type="text/css">
		<link rel="stylesheet" href="/assets/jquery.fancybox.css" type="text/css">
		<script src="/assets/modernizr.js" type="text/javascript"></script>
	</head>
	<body>

		<div id="container">
			<header id="header">
				<!-- <div class="pre-head show-on-mobile">
					<div class="wrap group">
						<div class="pre-head-wgt group">
							<aside class="widget group widget_ci_social_widget">
								<a href="#" class="icn twitter">Twitter</a><a href="#" class="icn facebook">Facebook</a><a href="#" class="icn pinterest">Pinterest</a><a href="#" class="icn youtube">Youtube</a>
							</aside>

							<aside class="widget widget_search group">
								<div id="user_nav">
									<%# if current_user %>
									<h1 style="font-size: 1.3em; margin: 0px">Signed in as <strong><%#= current_user.name %></strong>!</h1>
									<h1 style="font-size: 1.4em; margin: 0px; text-transform: uppercase"><a href="/questions/new" style="font-weight: bold">Post your question</a> |

									<%#= link_to "Sign out", signout_path, id: "sign_out" %></h1>
									<%# else %>
										<%#= link_to "Sign in with Facebook & Start posting", "/auth/facebook", id: "sign_in", :style => "font-weight:bold; font-size: 1.4em" %>
									<%# end %>
								</div>
							</aside>
						</div><! .header-wgt -->
					</div>
				</div><!-- .pre-head -->

				<div id="site-head">
					<div class="wrap group">
						<hgroup class="logo">
							<h1><a href="/"><img src="/assets/find-similar-logo.png" alt=""></a></h1>
						</hgroup>
					
						<div class="header-wgt group">
							<aside class="widget group widget_ci_social_widget">
								<a href="#" class="icn twitter">Twitter</a><a href="#" class="icn facebook">Facebook</a><a href="#" class="icn pinterest">Pinterest</a><a href="#" class="icn youtube">Youtube</a>
							</aside>
							
							<aside class="widget widget_search group">
								<div id="user_nav" style="text-align:right">
									<% if current_user %>
									<h1 style="font-size: 1.3em; margin: 0px">Signed in as <strong><%= current_user.name %></strong>!</h1>
									<h1 style="font-size: 1.4em; margin: 0px; text-transform: uppercase"><a href="/questions/new" style="font-weight: bold">Post your question</a> | 
									<%= link_to 'MY PROFILE', profile_path %> |
									<%= link_to "Sign out", signout_path, id: "sign_out" %></h1>
									<% else %>
										<%= link_to "Sign in with Facebook & Start posting", "/auth/facebook", id: "sign_in", :style => "font-weight:bold; font-size: 1.4em" %>
									<% end %>
								</div>
							</aside>
	
						</div><!-- .header-wgt -->
					</div><!-- .wrap < #header -->
				</div><!-- #site-head -->
				<nav>
					<div class="wrap group">
						<ul id="navigation" class="group">
							<li class="current_page_item">
								<a href="#">Home</a>
							</li>
							<li>
								<a href="/questions/new">Post your question</a>
							</li>
							<li>
								<a href="#">About</a>
							</li>
							<li>
								<a href="#">FAQ</a>
							</li>
							<li>
								<a href="#">Contact</a>
							</li>
						</ul>
					</div><!-- .wrap < nav -->
				</nav>
			</header>
			<div id="page">
				<section id="main">
					<div class="wrap group">
						<div id="box-container">
							<%= yield %>
						</div>
					</div><!-- .wrap < #main -->
				</section><!--  #main -->

				<footer id="footer">
					<div class="wrap group">
						<div class="footer-text">
							<a href="#">findsimilar</a> &mdash; get what you want.
						</div>
					</div>
					<div id="tmpFooter">
						<% flash.each do |name, msg| %>
							<%= content_tag :div, msg, id: "flash_#{name}" %>
						<% end %>
					</div>
				</footer>
			</div><!-- #page -->

		</div>
	</body>
</html>